### ISSUE TITLE
Downloading / Publishing YAML removes quotes from strings

### ISSUE THREAD

**Issue by matthew-muscat** [Apicurio/apicurio-studio#1005]
When downloading or publishing an project api specification, we're seeing previously quoted values being outputted without quotes.

This is in turn leading to a bug with the fields being incorrectly rendered in tooling such as redoc — which typically converts the YAML into a JSON object

A repeatable example can be seen over at https://onlineyamltools.com/convert-yaml-to-json using the following example payloads...

Quoted Date String
```
Priority Order request:
  value:
    order:
      courier_type: priority
      delivery_address: 1 Union Street
      delivery_postcode: "2009"
      delivery_state: NSW
      delivery_suburb: Pyrmont
      authority_to_leave: "Yes"
      delivery_date: "2016-07-26"
      delivery_window: 16:00-19:00
      parcel_attributes:
      - qty: 1
        weight: 2.1
```
 — delivery_date results in displaying as "2016-07-26"

Unquoted Date String

```
Priority Order request:
  value:
    order:
      courier_type: priority
      delivery_address: 1 Union Street
      delivery_postcode: "2009"
      delivery_state: NSW
      delivery_suburb: Pyrmont
      authority_to_leave: "Yes"
      delivery_date: 2016-07-26
      delivery_window: 16:00-19:00
      parcel_attributes:
      - qty: 1
        weight: 2.1
```
 — delivery_date results in displaying as "2016-07-26T00:00:00.000Z"
