### ISSUE TITLE
Support showing multiple example JSON bodies for a given Type/Endpoint

### ISSUE THREAD

**Issue by InfoSec812** [Apicurio/apicurio-studio#1083]
For example:

```
title: ContactMethod
description: A method for sending alerts for a given vehicle
required:
    - method
    - destination
    - vehicleId
type: object
properties:
    method:
        description: 'The method by which to send notifications about alerts. SMS (Text Message), E-Mail, or Mobile PUSH'
        enum:
            - SMS
            - EMAIL
            - PUSH
        type: string
    vehicleId:
        description: The UUID identifying the vehicle
        type: string
    destination:
        description: >-
            The destination. A phone number for SMS, and e-mail address for EMAIL, or a mobile device ID for
            PUSH.
        type: string
examples:
    sms:
        method: SMS
        vehicleId: 27386c3a-5ef0-11ea-89fa-976868bb9fe6
        destination: '8005551212'
    email:
        method: EMAIL
        vehicleId: 27386c3a-5ef0-11ea-89fa-976868bb9fe6
        destination: 'jdoe@example.com'
```
