### ISSUE TITLE
Does not support array of enum

### ISSUE THREAD

**Issue by t-l-smith** [Apicurio/apicurio-studio#1197]
In a parameter entry I have imported this:
```
        -
            name: status
            description: 'optional process instance status (active, completed, aborted) - defaults ot active (1) only'
            in: query
            required: false
            type: array
            items:
                type: integer
                format: int32
                enum:
                    - 1
                    - 2
                    - 3
            collectionFormat: multi
```
Apicurio correctly detects and handles the Array aspect, but ignores the enum (& I think the `collectionFormat` tag?)

This example is imported from RedHat KieServer swagger.json (attached)
[swagger.json.txt](https://github.com/Apicurio/apicurio-studio/files/4834596/swagger.json.txt)
