### ISSUE TITLE
Editor: Source disappears when not valid OpenAPI markup

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#139]
* Create a new definition `policies`
* Add the following YAML definition via the `Source` tab:

```yaml
policies:
  title: Policies
  type: array
  items:
    title: Policy
    type: object
    required:
    - policyJsonConfig
    - policyImpl
    items:
      policyJsonConfig:
        title: Policy JSON config
        description: The policy's escaped/serialised configuration.
        type: string
        minLength: 1
      policyImpl:
        title: Policy implementation.
        description: Policy implementation coordinates
        type: string
        minLength: 1
```

* Click `Save`
* Navigate to a path entry (e.g. `/apis`)
* Navigate back to the `policies` definition.
* Click `source`
* It's now empty, just a pair of empty braces `{}`.
* No errors present on the console

**Comment by msavy** [comment]
Just a thought -- why not add labels for api-editor, api-studio, api-hub, etc. Should filter more readily.

**Comment by msavy** [comment]
Hmm, if I leave the top level bit out and just put the element from title onwards then it zaps the rest of the definition and only leaves this:

```
title: Policies
type: array
items:
    title: Policy
    required:
        - policyJsonConfig
        - policyImpl
    type: object
    items: {}
```

Strange
