### ISSUE TITLE
API Editor: Invalid syntax produced for array containing reference

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#143]
* Create definition `policy`.
* Create definition `policies` with array of `policy`.
* Following invalid spec will be produced:

```yaml
properties:
    policies:
        type: array
        items:
            type: '#/definitions/policy'
```

According to _the apicurio guy_ (@EricWittmann), `type` should be `$ref` on the last line of the snippet 🤠
