### ISSUE TITLE
API Editor: securityDefinitions BASIC output violates spec

### ISSUE THREAD

**Issue by msavy** [Apicurio/apicurio-studio#145]
![image](https://user-images.githubusercontent.com/423513/28164449-5270e4a4-67c7-11e7-8f5c-b7abc74ec00a.png)

Produces:

```yaml
securityDefinitions:
  Standard BASIC:
    type: basic
    description: |-
      The standard auth configuration for apiman gateway is BASIC. This is usually in concert with Keycloak and must be a user with the `apipublisher` role. 

      In the quickstart this is `apimanager/apiman123!`.
     
    scopes: {} // <--- This is the culprit; should not be here.
  Keycloak OAuth2:
    type: oauth2
    description: |-
      The Apiman Gateways can be configured to use various OAuth2 implementations instead BASIC. Refer to the Gateway API Auth documentation for more information.

      The user must have the `apipublisher` role.
    flow: implicit
    authorizationUrl: 'https://keycloak-server.local/path/for/your/realm/and/auth/type'
    scopes: {}
```

Error:

`scopes: {}` should not be present for BASIC, as I understand the spec (and seems to work after removing). I've annotated the sample above.
