### ISSUE TITLE
Standalone Template failing to deploy Postgres

### ISSUE THREAD

**Issue by raffamendes** [Apicurio/apicurio-studio#1505]
Hi,

I was just deploying Apicurio Studio on Openshift 4.6 Cluster using the standalone template and the postgresql pod never started because of unresolved image, I think that it's because of this spec on the pod template:
```yaml
 containers:
          - name: postgresql
            image: centos/postgresql-95-centos7
            ports:
              - containerPort: 5432
                protocol: TCP
            env:
```
I got it working by changing it to this:
```yaml
containers:
          - name: postgresql
            image: postgresql:9.6-el8
            ports:
              - containerPort: 5432
                protocol: TCP
            env:
```

Is this worth a PR? I think that the image could be a template Parameter.

I can make this modifications if you guys think this should be this way.

Regards
