### ISSUE TITLE
Support multipart/form-data in UI designer

### ISSUE THREAD

**Issue by tillias** [Apicurio/apicurio-studio#1592]
Hello!

I'm trying to visually design object schema for multipart/form-data, and it seems there is no possibility to define it in UI editor:

https://github.com/OpenAPITools/openapi-generator/issues/6677

When I try to append from source code view it is erased:

```
 type: object
              properties:
                file:
                  type: string
                  description: Source file to be uploaded
                  format: binary
```

Without type=object, properties: ... it is not possible to use openAPI document for code-generation (parameter "file" is missing)
