### ISSUE TITLE
Editor flags oneOf / anyOf as issue on array items

### ISSUE THREAD

**Issue by Stwissel** [Apicurio/apicurio-studio#1805]
We have a need to specify a data type `array` where the members [must be of one type](https://stackoverflow.com/questions/71021191/limit-type-of-jsonarray-elements-to-the-same-type-but-not-limit-types). When adding such a definition:

```yaml
            type: array
            anyOf:
                -
                    items:
                        type: number
                -
                    items:
                        type: string
```

the editor flags it as issue:

- Schema is missing array type information. <br />No additional information found.
- Schema items must be present only for schemas of type 'array'.<br />No additional information found.
- Schema items must be present only for schemas of type 'array'.<br />No additional information found.

When I add another type for items, the second error gets repeated once more.

I check the result: The swagger editor loads it, the online validator is happy, ReDoc correctly identifies it (see screenshot below - from an extended example). Is this a bug in the Editor?

![Screenshot 2022-02-08 at 11 15 50 PM](https://user-images.githubusercontent.com/542549/153016730-ac43e753-db18-4883-9096-0cdcf62811b7.png)
