### ISSUE TITLE
CORS Rejection Issue When Hosting Apicurio Studio with Docker-Compose

### ISSUE THREAD

**Issue by fclef819** [Apicurio/apicurio-studio#2222]
I'm trying to host Apicurio Studio using Docker-Compose, but I'm encountering a CORS rejection issue when loading js and css files after logging in. Could anyone advise me on what I need to modify to resolve this issue?

I would appreciate it if you could provide any insights or suggestions.

Thank you in advance.

# setting files

docker-compose.yml
```
version: '3'
services:
...
    apicurio-api:
        logging:
            driver: json-file
            options:
                max-file: '1'
                max-size: 3m
        image: apicurio/apicurio-studio-api
        restart: always
        environment:
            APICURIO_KC_AUTH_URL: https://keycloak.example.com
            APICURIO_KC_REALM: apicurio
            APICURIO_HUB_STORAGE_JDBC_TYPE: postgresql9
            APICURIO_DB_DRIVER_NAME: postgresql
            APICURIO_DB_CONNECTION_URL: jdbc:postgresql://pg:5432/apicurio
            APICURIO_DB_USER_NAME: psql
            APICURIO_DB_PASSWORD: password
            APICURIO_DB_INITIALIZE: "true"
            APICURIO_HUB_STORAGE_JDBC_INIT: "true"
            APICURIO_GITLAB_API_URL: https://gitlab.example.com
            QUARKUS_PROFILE: prod
        depends_on:
            - pg
            - apicurio-ws

    apicurio-ws:
        logging:
            driver: json-file
            options:
                max-file: '1'
                max-size: 3m
        image: apicurio/apicurio-studio-ws
        restart: always
        environment:
            APICURIO_KC_AUTH_URL: https://keycloak.example.com
            APICURIO_KC_REALM: apicurio
            APICURIO_HUB_STORAGE_JDBC_TYPE: postgresql9
            APICURIO_DB_DRIVER_NAME: postgresql
            APICURIO_DB_CONNECTION_URL: jdbc:postgresql://pg:5432/apicurio
            APICURIO_DB_USER_NAME: psql
            APICURIO_DB_PASSWORD: password
            APICURIO_DB_INITIALIZE: "true"
            APICURIO_HUB_STORAGE_JDBC_INIT: "true"
            QUARKUS_PROFILE: prod
        depends_on:
            - pg

    apicurio-ui:
        logging:
            driver: json-file
            options:
                max-file: '1'
                max-size: 3m
        image: apicurio/apicurio-studio-ui
        restart: always
        environment:
            HOSTNAME: apicurio.example.com
            APICURIO_KC_AUTH_URL: https://keycloak.example.com
            APICURIO_KC_REALM: apicurio
            APICURIO_UI_HUB_API_URL: https://apicurio.example.com/api
            APICURIO_UI_EDITING_URL: https://apicurio.example.com/ws
            APICURIO_GITLAB_API_URL: https://gitlab.example.com
            APICURIO_GITLAB_URL: https://gitlab.example.com
            QUARKUS_PROFILE: prod
            APICURIO_OIDC_REDIRECT_HTTPS: "false"
            APICURIO_KC_SSL_REQUIRED: "true"
            APICURIO_LOGGING_LEVEL: DEBUG
        depends_on:
            - pg
            - apicurio-api
            - apicurio-ws

    keycloak:
        logging:
            driver: json-file
            options:
                max-file: '1'
                max-size: 3m
        image: quay.io/keycloak/keycloak:latest
        restart: always
        environment:
            KC_HOSTNAME: keycloak.example.com
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
            KEYCLOAK_IMPORT: /microcks-keycloak-config/apicurio-realm.json,/microcks-keycloak-config/microcks-realm.json
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://pg:5432/keycloak
            KC_DB_USERNAME: psql
            KC_DB_PASSWORD: password
            KC_HTTP_ENABLED: "true"
            KC_PROXY: edge
        user: "0:0"
        command:
            - start
            - --https-certificate-file=/etc/x509/https/fullchain.pem
            - --https-certificate-key-file=/etc/x509/https/privkey.pem
            - --import-realm
        volumes:
            - /home/me/docker/server/keycloak/apicurio-realm.json:/opt/keycloak/data/import/apicurio-realm.json
            - /home/me/docker/server/keycloak/microcks-realm.json:/opt/keycloak/data/import/microcks-realm.json
            - /etc/letsencrypt/live/example.com/fullchain.pem:/etc/x509/https/fullchain.pem
            - /etc/letsencrypt/live/example.com/privkey.pem:/etc/x509/https/privkey.pem
...
```

nginx setting file
```
server {
    listen       80;
    listen [::]:80;
    server_name  apicurio.example.com;
    include /etc/nginx/params/hsts_params;
    return 301 https://$host$request_uri;
}
server {
    listen       443 ssl;
    listen [::]:443 ssl;
    server_name  apicurio.example.com;
    include /etc/nginx/params/examplecom_ssl_params;

    location / {
        include /etc/nginx/params/proxy_params;
        proxy_pass http://apicurio-ui:8080;
    }

    location /studio {
        return 301 https://$host:8080;
    }

    location ^~ /api {
        rewrite ^/api(.*)$ $1 break;
        include /etc/nginx/params/proxy_params;
        proxy_pass http://apicurio-api:8080;
    }                                                                                     

    location ^~ /ws {
        rewrite ^/ws(.*)$ $1 break;
        include /etc/nginx/params/proxy_params;
        include /etc/nginx/params/ws_params;
        proxy_pass http://apicurio-ws:8080;
    }
}

server {
    listen       80;
    listen [::]:80;
    server_name  keycloak.example.com;
    include /etc/nginx/params/hsts_params;
    return 301 https://$host$request_uri;
}
server {
    listen       443 ssl;
    listen [::]:443 ssl;
    server_name  keycloak.example.com;

    include /etc/nginx/params/examplecom_ssl_params;

    location / {
        include /etc/nginx/params/proxy_params;
        proxy_pass http://keycloak:8080;
    }
}
```
