### ISSUE TITLE
 Error: Registry configuration "draft mutability"

### ISSUE THREAD

**Issue by dbalboa777** [Apicurio/apicurio-studio#2968]
Studio failed to load because the Registry application is not properly configured. In order for Studio to work, the Registry application must have the "draft mutability" option enabled. This option must be enabled when installing/deploying Registry.

The following option should be set to true:

apicurio.rest.mutability.artifact-version-content.enabled

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-studio-ui
  labels:
    app: apicurio-studio-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-studio-ui
  template:
    metadata:
      labels:
        app: apicurio-studio-ui
    spec:
      containers:
        - name: apicurio-studio-ui
          image: quay.io/apicurio/apicurio-studio-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: APICURIO_UI_BACKEND_URL
              value: "http://your_URL:8080" 
            - name: APICURIO_REST_MUTABILITY_ARTIFACT_VERSION_CONTENT_ENABLED
              value: 'true'

installation in openshift

**Comment by MikhailDeriabin** [comment]
Apparently they are moving to a new tech stack and rewriting the whole app code base. The new version tag ATM that should be used is _1.0.0.Beta1_.

Here is my docker compose file:

```
services:
  postgresql:
    container_name: apicurio-studio-postgresql
    image: postgres:16
    environment:
      POSTGRES_USER: apicurio-studio
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - apicurio-db:/var/lib/postgresql/data

  app:
    image: quay.io/apicurio/apicurio-studio:1.0.0.Beta1
    environment:
      APICURIO_LOG_LEVEL: DEBUG
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_ACCESS-LOG_ENABLED: 'true'
      QUARKUS_HTTP_CORS_ORIGINS: '*'
      APICURIO_STORAGE_DB_KIND: postgresql
      APICURIO_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/apicurio-studio
      APICURIO_DATASOURCE_USERNAME: apicurio-studio
      APICURIO_DATASOURCE_PASSWORD: password
    ports:
      - '8887:8080'
    depends_on:
      - postgresql

  ui:
    image: quay.io/apicurio/apicurio-studio-ui:1.0.0.Beta1
    environment:
      APICURIO_STUDIO_API_URL: http://localhost:8887/apis/studio/v1
    ports:
      - '8888:8080'
    depends_on:
      - app

volumes:
  apicurio-db:

```
