### ISSUE TITLE
How to tag an api operation?

### ISSUE THREAD

**Issue by allanic79** [Apicurio/apicurio-studio#333]
I created several tags on top level. But I didn't find a way to apply them on individual api. For example, to add "tags" under operation level like below: 
```
  /path:
    get:
      tags:
      - some_tag
      summary: 
```
Is it currently possible?
