### ISSUE TITLE
Editor: Required properties deleted from Data Types still referenced in downloaded YAML

### ISSUE THREAD

**Issue by mmindenhall** [Apicurio/apicurio-studio#483]
I have been using the tool to design a new API (love it so far!).

I had the need to change my property names from snake_case to camelCase to be consistent with another project.  Since renaming is "Not yet implemented", I created a new property (e.g., `fileType`), then copied the description, whether Required, and Type from the existing `file_type` property.  I then deleted the `file_type` property.

However, `file_type` when I download the YAML, the deleted property name is still present (along with the new property name):

```yaml
    DataSource:
      required:
      - file_type
      - fileType
      - tenantId
```

The old name is only referenced within the `required` list (it was correctly removed from the `properties` list).
