### ISSUE TITLE
[Feature Request] Do not delete unsupported valid OAI tags from source.

### ISSUE THREAD

**Issue by Kiran-B** [Apicurio/apicurio-studio#634]
Use case:
The studio at the moment does not support re-usable Headers, Params etc. So when importing specs that includes those tags, studio deletes references for those. Example if imported spec had a following spec definition:
paths:
```yaml
    '/pets/{id}':
        summary: 'Path used to manage Pets.'
        parameters:
            - $ref: '#/components/parameters/content-type-header'
            - name: id
              in: path
```
after the import it becomes:
```yaml
    '/pets/{id}':
        summary: 'Path used to manage Pets.'
        parameters:
            -  name: id
               in: path
```
The parameter with $ref is removed.

The studio at the moment does not support re-usable Headers, Params etc which is captured in #240, #241, #242, #243, #244, #245, #246. 

Feature requested:
Until these are resolved, could the studio not delete those valid tags from the source?
This would allow portability of source across multiple tools.
