### ISSUE TITLE
Wildfly issue with docker

### ISSUE THREAD

**Issue by chriske** [Apicurio/apicurio-studio#682]
Hi,

today I wanted to make an experiment. I started to create a docker-compose file to be able to run Apicurio and Microcks from "one place" (and a reverse proxy later with SSL). I used your docker images from dockerhub.

Unfortunately currently - at least in my configuration (Ubunu 16.04) - the docker images are not working.

Every 3 spring boot app started with an unknown protocol family error when they wanted to open the socket.
After some googling I found the issue:

https://www.sipmann.com/socketException-protocol-family-unavailable-java-docker-wildfly.html#.XIVEAnVKhhF

In my docker-compose setup I rewrote your entrypoint, and now your applications are starting up.
Here is an example:

```
apicurio-ws:
    depends_on:
      - postgresql
    image: apicurio/apicurio-studio-ws:0.2.23.Final
    container_name: apicurio-ws    
    ports:
      - "8082:8080"
    environment:
      - APICURIO_DB_DRIVER_NAME=postgresql
      - APICURIO_DB_CONNECTION_URL=jdbc:postgresql://postgresql:5432/apicurio
      - APICURIO_DB_TYPE=postgresql9
      - APICURIO_DB_USER_NAME=apicurio
      - APICURIO_DB_PASSWORD=123
    entrypoint:
      - java
      - -Djava.net.preferIPv4Stack=true
      - -Djava.net.preferIPv4Addresses=true
      - -jar
      - /opt/apicurio/apicurio-studio-ws-thorntail.jar
    networks:
      main:
        aliases:
          - apicurio-ws
```
Maybe you should consider to add these parameters to your own Dockerfile, or change the plugin settings in the pom as it is mentioned in the article above.

Thanks, and keep up the good work!

**Comment by EricWittmann** [comment]
Thanks for the information!

**Comment by EricWittmann** [comment]
Also - did you get a docker compose working with everything together?  If so, that'd be a fantastic contribution back to Apicurio and Microcks!  :)

**Comment by Nicnl** [comment]
Just a quick follow up to this  

You don't need to rewrite the whole entrypoint  
You can just set the environment variable `JAVA_TOOL_OPTIONS` with your JVM arguments

Here is what my compose looks like

```yml
version: '3'

services:
  apicurio-studio-ws:
    image: 'apicurio/apicurio-studio-ws:0.2.23.Final'
    ports:
      - '8092:8080'
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'

      APICURIO_DB_TYPE: 'mysql5'
      APICURIO_DB_DRIVER_NAME: 'mysql'
      APICURIO_DB_CONNECTION_URL: 'jdbc:mysql://apicurio-studio-mysql/apicuriodb'
      APICURIO_DB_USER_NAME: 'apicurio'
      APICURIO_DB_PASSWORD: '----------'
      APICURIO_DB_INITIALIZE: 'false'
```

When I start my container, the environment variable is picked up and loaded  

```
apicurio-studio-ws_1     | Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
[...]
apicurio-studio-ws_1     | 2019-03-12 12:50:21,765 INFO  [org.wildfly.swarm] (MSC service thread 1-2) THORN0019: Install MSC service for command line args: [-Xms768m, -Xmx2048m, -Dthorntail.port.offset=0, -Dthorntail.datasources.data-sources.ApicurioDS.driver-name=mysql, -Dthorntail.datasources.data-sources.ApicurioDS.connection-url=jdbc:mysql://apicurio-studio-mysql/apicuriodb, -Dthorntail.datasources.data-sources.ApicurioDS.user-name=apicurio, -Dthorntail.datasources.data-sources.ApicurioDS.password=----------, -Dapicurio.hub.storage.jdbc.init=false, -Dapicurio.hub.storage.jdbc.type=mysql5, -Dthorntail.logging=INFO]
```
