### ISSUE TITLE
Missing braces on value inside Example object

### ISSUE THREAD

**Issue by sercastiGL** [Apicurio/apicurio-studio#737]
Following the OpenAPI spec here: https://github.com/Apicurio/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject

the Example object uses a value field, which should use braces { } 

Currently generating an example for a single object with apicurio generates this:

```yaml
    examples:
        MyExample:
            value:
                -
                    id: 1
                    name: Carol
                    lastname: Danvers
                    email: carol.danvers@gmail.com
                    mentor: Ororo Munroe
                    lastConnection: '2019-01-11'
                    avatarId: 1
```

Which fails to be interpreted as a valid mock example response by microcks, as it is non-spec compatible

Correct syntax is:

```yaml
    examples:
        MyExample:
            value:  {
                -
                    id: 1
                    name: Carol
                    lastname: Danvers
                    email: carol.danvers@gmail.com
                    mentor: Ororo Munroe
                    lastConnection: '2019-01-11'
                    avatarId: 1
            }
```
