### ISSUE TITLE
x.slice is not a function

### ISSUE THREAD

**Issue by bpeterm** [Apicurio/apicurio-studio#748]
Hello,

When I'd like to Preview Documentation, I show this error:

Something went wrong...
x.slice is not a function
Stack trace
TypeError: x.slice is not a function
    at Object.matchGrammar (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:26236)
    at Object.tokenize (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:26564)
    at Object.highlight (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:55:25251)
    at at (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:108:31856)
    at t.render (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:114:76644)
    at ji (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:83:62905)
    at Ai (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:83:62700)
    at Ri (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:83:66534)
    at Ha (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:83:90551)
    at Va (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:83:90935)

ReDoc Version: 2.0.0-rc.4 
Commit: 0dab8af

There's no Issues in the editor.

Thanks,
Peter

**Comment by bpeterm** [comment]
There was a wrong multipart/form-data example of a POST operation.
It cannot be in JSON format, just in bulk text format.

**Comment by EricWittmann** [comment]
This sounds like a bug in [ReDoc](https://github.com/Rebilly/ReDoc/issues).  Do you agree?

**Comment by bpeterm** [comment]
> This sounds like a bug in [ReDoc](https://github.com/Rebilly/ReDoc/issues). Do you agree?

It can be JSON format in multipart/form-data example? I didn't find in specification...

**Comment by EricWittmann** [comment]
Can you include a simple OpenAPI document that reproduces the problem?

**Comment by EricWittmann** [comment]
Just following up on this - @bpeterm can you supply a reproducer for this?

**Comment by paflov** [comment]
I had the same problem. Reproduction and workaround is easy:

This:

```
        "201":
          description:  OK, started
          content:
            text/plain:
              example: 1
```

causes the error, but this

```
        "201":
          description:  OK, started
          content:
            text/plain:
              example: "1"
```

works.

Redoc "2.0.0-rc.22"
