### ISSUE TITLE
Schema items must be present only for schemas of type 'array'.

### ISSUE THREAD

**Issue by bpeterm** [Apicurio/apicurio-studio#749]
The requestBody at multipart/form-data content schema cannot be a reference type.

**Comment by EricWittmann** [comment]
I think I understand what you're reporting here, but could you create an OpenAPI document that reproduces the problem?

**Comment by kino90** [comment]
I'm having tons of this, too (only in newly added Data Types)

For example I'm getting this for each property of this Data Type:

```
type: object
properties:
    passwordPolicyRegex:
        type: string
    passwordPolicyDescription:
        type: string
```

![image](https://user-images.githubusercontent.com/1820036/57130418-b2480900-6d99-11e9-8c66-9f802cc4d389.png)
