### ISSUE TITLE
[feature] enum: description and value

### ISSUE THREAD

**Issue by jmini** [Apicurio/apicurio-studio#829]
The OpenAPI is not really supporting Enum with description and value.

There is an OpenAPI discussion (https://github.com/OAI/OpenAPI-Specification/issues/681#issuecomment-438503247) suggesting that this notation could be used:
```yaml
oneOf:
  - enum: [1]
    title: Sunny
    description: Blue sky
  - enum: [2]
    title: Cloudy
    description: Slightly overcast
  - enum: [3]
    title: Rainy
    description: Take an umbrella with you
```

Other tool (OpenAPI-Generator) uses following extensions `x-enum-descriptions` and `x-enum-varnames`:

```yaml
WeatherType:
  type: integer
  format: int32
  enum:
    - 1
    - 2
    - 3
  x-enum-descriptions:
    - 'Blue sky'
    - 'Slightly overcast'
    - 'Take an umbrella with you'
  x-enum-varnames:
    - Sunny
    - Cloudy
    - Rainy
```
