### ISSUE TITLE
rfe - specify maxLength for string type

### ISSUE THREAD

**Issue by mattf** [Apicurio/apicurio-studio#857]
```yaml
paths:
  /test/{id}:
    get:
      parameters:
      - name: id
        schema:
          type: string
          maxLength: 42
        in: path

components:
  schemas:
    Test:
      type: object
      properties:
        id:
          type: string
          maxLength: 42
```

maxLength is a valid [schema property](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties) that i would like to be able to specify.
